export const vocabData = [
    // --- UNIT 1: C'est la rentrée! ---
    // Page 182
    { id: 101, french: "la rentrée", german: "der Schul(jahres)beginn", type: "noun" },
    { id: 102, french: "un nom", german: "ein Name", type: "noun" },
    { id: 103, french: "une liste", german: "eine Liste", type: "noun" },
    { id: 104, french: "environ", german: "ungefähr; etwa", type: "adv" },
    { id: 105, french: "la cinquième", german: "die Fünfte; die fünfte Klasse", type: "noun" },
    { id: 106, french: "en 5e", german: "in der fünften Klasse", type: "phrase" },

    // Mes affaires pour l'école (Page 183)
    { id: 107, french: "un cahier", german: "ein Heft", type: "noun" },
    { id: 108, french: "un crayon", german: "ein Bleistift", type: "noun" },
    { id: 109, french: "un stylo", german: "ein Kuli", type: "noun" },
    { id: 110, french: "un livre", german: "ein Buch", type: "noun" },
    { id: 111, french: "une gomme", german: "ein Radiergummi", type: "noun" },
    { id: 112, french: "un effaceur", german: "ein Tintenlöscher; ein Tintenkiller", type: "noun" },
    { id: 113, french: "une règle", german: "ein Lineal", type: "noun" },
    { id: 114, french: "une trousse", german: "ein Federmäppchen", type: "noun" },
    { id: 115, french: "un feutre", german: "ein Filzstift", type: "noun" },
    { id: 116, french: "un sac à dos", german: "ein Rucksack", type: "noun" },
    { id: 117, french: "un ordinateur", german: "ein Computer", type: "noun" },
    { id: 118, french: "une tablette", german: "ein Tablet", type: "noun" },
    { id: 119, french: "une feuille", german: "ein Blatt Papier", type: "noun" },

    // Les nombres ordinaux (Page 183)
    { id: 120, french: "le premier / la première", german: "der/die/das Erste", type: "number" },
    { id: 121, french: "le second / la seconde", german: "der/die/das Zweite", type: "number" },
    { id: 122, french: "le / la deuxième", german: "der/die/das Zweite", type: "number" },
    { id: 123, french: "le / la troisième", german: "der/die/das Dritte", type: "number" },
    { id: 124, french: "le / la quatrième", german: "der/die/das Vierte", type: "number" },
    { id: 125, french: "le / la cinquième", german: "der/die/das Fünfte", type: "number" },
    { id: 126, french: "le / la sixième", german: "der/die/das Sechste", type: "number" },
    { id: 127, french: "le / la septième", german: "der/die/das Siebte", type: "number" },
    { id: 128, french: "le / la huitième", german: "der/die/das Achte", type: "number" },
    { id: 129, french: "le / la neuvième", german: "der/die/das Neunte", type: "number" },
    { id: 130, french: "le / la dixième", german: "der/die/das Zehnte", type: "number" },
    { id: 131, french: "le / la onzième", german: "der/die/das Elfte", type: "number" },

    // Pronouns (Page 182)
    { id: 132, french: "lui", german: "er (betont)", type: "pronoun" },
    { id: 133, french: "eux", german: "sie (betont) (m.) (Pl.)", type: "pronoun" },

    // Page 184
    { id: 134, french: "savoir", german: "wissen", type: "verb" },
    { id: 135, french: "savoir faire qc", german: "etwas tun können (wissen, wie etwas geht)", type: "verb" },
    { id: 136, french: "une blague", german: "ein Scherz; ein Streich", type: "noun" },
    { id: 137, french: "vrai / vraie", german: "wahr; richtig; echt", type: "adj" },
    { id: 138, french: "avoir l'air", german: "aussehen", type: "verb" },
    { id: 139, french: "un exemple", german: "ein Beispiel", type: "noun" },
    { id: 140, french: "la colère", german: "der Zorn; die Wut", type: "noun" },
    { id: 141, french: "être en colère", german: "wütend sein", type: "phrase" },
    { id: 142, french: "bête", german: "dumm; blöd", type: "adj" },
    { id: 143, french: "par exemple", german: "zum Beispiel", type: "phrase" },
    { id: 144, french: "le même / la même", german: "derselbe/dasselbe/dieselbe; das Gleiche/der Gleiche/die Gleiche", type: "adj" },
    { id: 145, french: "connaître qn/qc", german: "jemanden/etwas kennen", type: "verb" },
    { id: 146, french: "comprendre qc", german: "etwas verstehen", type: "verb" },
    { id: 147, french: "là-bas", german: "da(hin); dort (drüben)", type: "adv" },
    { id: 148, french: "à côté de", german: "neben", type: "prep" },
    { id: 149, french: "un nouveau / une nouvelle", german: "ein Neuer / eine Neue", type: "noun" },
    { id: 150, french: "la tête", german: "der Kopf; hier: das Gesicht", type: "noun" },
    { id: 151, french: "On y va", german: "Gehen wir!; Auf geht's!", type: "phrase" },
    { id: 152, french: "en cours", german: "im Unterricht; in den Unterricht", type: "phrase" },
    { id: 153, french: "sans", german: "ohne", type: "prep" },
    { id: 154, french: "drôle", german: "lustig", type: "adj" },
    { id: 155, french: "tout", german: "alles", type: "pronoun" },
    { id: 156, french: "une différence", german: "ein Unterschied", type: "noun" },
    { id: 157, french: "faire la différence (entre)", german: "unterscheiden (zwischen)", type: "verb" },

    // Page 185
    { id: 158, french: "vouloir dire", german: "meinen; bedeuten", type: "verb" },
    { id: 159, french: "qui", german: "der/die/das (Relativpronomen)", type: "pronoun" },
    { id: 160, french: "que", german: "den/die/das (Relativpronomen)", type: "pronoun" },
    { id: 161, french: "mettre qc", german: "etwas stellen; etwas legen", type: "verb" },
    { id: 162, french: "penser à qn", german: "an jdn. denken", type: "verb" },
    { id: 163, french: "une boulette", german: "ein Kügelchen", type: "noun" },
    { id: 164, french: "le papier", german: "das Papier", type: "noun" },
    { id: 165, french: "un acteur / une actrice", german: "ein Schauspieler / eine Schauspielerin", type: "noun" },
    { id: 166, french: "sur Internet", german: "im Internet", type: "phrase" },
    { id: 167, french: "timide", german: "schüchtern", type: "adj" },
    { id: 168, french: "la poubelle", german: "der Mülleimer; der Papierkorb", type: "noun" },
    { id: 169, french: "continuer", german: "weitermachen; fortfahren", type: "verb" },
    { id: 170, french: "où", german: "wo (Relativpronomen)", type: "pronoun" },
    { id: 171, french: "avoir cours", german: "Unterricht haben", type: "verb" },
    { id: 172, french: "un mot de passe", german: "ein Passwort", type: "noun" },
    { id: 173, french: "un résultat", german: "ein Ergebnis", type: "noun" },
    { id: 174, french: "ressembler à qn/qc", german: "jdm./etw. ähnlich sein", type: "verb" },
    { id: 175, french: "être né(e)", german: "geboren werden/sein", type: "verb" },
    { id: 176, french: "mille", german: "tausend", type: "number" },
    { id: 177, french: "en deux mille", german: "im Jahr 2000", type: "phrase" },

    // Page 186
    { id: 180, french: "possible", german: "möglich", type: "adj" },
    { id: 181, french: "une star", german: "ein Star", type: "noun" },
    { id: 182, french: "un cinéma", german: "ein Kino", type: "noun" },
    { id: 183, french: "une devinette", german: "ein Rätsel", type: "noun" },
    { id: 184, french: "présenter qc/qn à qn", german: "jdm. jdn./etw. vorstellen", type: "verb" },
    { id: 185, french: "deviner qc", german: "etw. erraten", type: "verb" },
    { id: 186, french: "décrire qn/qc", german: "jdn./etw. beschreiben", type: "verb" },
    { id: 187, french: "un homme", german: "ein Mann", type: "noun" },
    { id: 188, french: "une femme", german: "eine Frau", type: "noun" },
    { id: 189, french: "un œil / des yeux", german: "ein Auge / Augen", type: "noun" },

    // Colors / Features (Page 186)
    { id: 190, french: "marron", german: "braun", type: "adj" },
    { id: 191, french: "un cheveu / des cheveux", german: "ein Haar / Haare", type: "noun" },
    { id: 192, french: "blond / blonde", german: "blond", type: "adj" },
    { id: 193, french: "brun / brune", german: "dunkelbraun", type: "adj" },
    { id: 194, french: "roux / rousse", german: "rot(haarig)", type: "adj" },

    { id: 195, french: "mal", german: "schlecht", type: "adv" },
    { id: 196, french: "le premier plan", german: "der Vordergrund", type: "noun" },
    { id: 197, french: "un centre", german: "ein Zentrum; eine Mitte; ein Mittelpunkt", type: "noun" },
    { id: 198, french: "l'arrière-plan", german: "der Hintergrund", type: "noun" },

    // Page 187
    { id: 199, french: "faire un cadeau à qn", german: "jdm. etw. schenken", type: "verb" },
    { id: 200, french: "avoir un cadeau", german: "etw. geschenkt bekommen", type: "verb" },
    { id: 201, french: "passer du bon temps avec qn", german: "mit jdm. eine gute Zeit verbringen", type: "verb" },
    { id: 202, french: "être sympa avec qn", german: "nett zu jdm. sein", type: "verb" },
    { id: 203, french: "avoir des bons résultats en classe", german: "gute Noten in der Schule haben", type: "verb" },
    { id: 204, french: "ne pas fonctionner", german: "nicht funktionieren", type: "verb" },
    { id: 205, french: "perdre un match (de foot)", german: "ein (Fußball-)Spiel verlieren", type: "verb" },
    { id: 206, french: "arriver en retard", german: "zu spät kommen", type: "verb" },
    { id: 207, french: "être de mauvaise humeur", german: "schlechte Laune haben", type: "phrase" },

    // --- UNIT 2: Lyon mystérieux ---
    // Page 187
    { id: 208, french: "un voyage", german: "eine Reise", type: "noun" },
    { id: 209, french: "un endroit", german: "ein Ort", type: "noun" },
    { id: 210, french: "un guide", german: "ein Führer", type: "noun" },
    { id: 211, french: "visiter qc", german: "etw. besichtigen", type: "verb" },
    { id: 212, french: "détester qn/qc", german: "jdn./etw. verabscheuen", type: "verb" },
    { id: 213, french: "oublier de faire qc", german: "vergessen etw. zu tun", type: "verb" },
    { id: 214, french: "là-bas", german: "dort(hin)", type: "adv" }, // Repeated but in context
    { id: 215, french: "surtout", german: "vor allem", type: "adv" },
    { id: 216, french: "mystérieux / mystérieuse", german: "geheimnisvoll; seltsam; mysteriös", type: "adj" },
    { id: 217, french: "la lumière", german: "das Licht", type: "noun" },
    { id: 218, french: "les frères Lumière", german: "die Brüder Lumière", type: "noun" },
    { id: 219, french: "un tunnel", german: "ein Tunnel", type: "noun" },
    { id: 220, french: "un souterrain", german: "ein unterirdischer Gang", type: "noun" },
    { id: 221, french: "une traboule", german: "Verbindungsgang; Besonderheit in der Altstadt von Lyon", type: "noun" }
];
